name: mod-build
on:
  push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK 11
      uses: actions/setup-java@v3.3.0
      with: 
        java-version: '11'
        distribution: 'temurin'
        java-package: jdk
    - name: Setup Java JDK 18
      uses: actions/setup-java@v3.3.0
      with: 
        java-version: '18'
        distribution: 'temurin'
        java-package: jdk
    - name: Setup Java JDK 8
      uses: actions/setup-java@v3.3.0
      with: 
        java-version: '8'
        distribution: 'temurin'
        java-package: jdk 
    - name: build
      run: |
        sh ./gradlew build --refresh-dependencies -Dfile.encoding=UTF-8 --info
        cp -rf ./build/libs /opt/build
    - name : Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: /opt/libs/
